#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := wsn_sensor_lpn_node

EXTRA_COMPONENT_DIRS := $(IDF_PATH)/examples/bluetooth/esp_ble_mesh/common_components/example_init \
                        $(IDF_PATH)/examples/bluetooth/esp_ble_mesh/common_components/fast_provisioning

include $(IDF_PATH)/make/project.mk

